### ISSUE TITLE
exception when ready

### ISSUE THREAD

**Issue by DavidBruchmann** [jitesoft/php-xml2array#2]
When the Parser is finished it throws an exception:
```
        if ($root['type'] !== self::OPEN) {
            throw new Exception("Unexpected error");
        }
```
Here you should just write this:

```
        if ($root['type'] !== self::OPEN) {
            return;
        }
```
Don't know if there is a possibility that an error occurs at this location but then a further check had to be included.

**Comment by DavidBruchmann** [comment]
Happens only when project is cloned instead of installed by composer.

**Comment by Johannestegner** [comment]
Could you possibly give an example xml file that I could test with and let me know which version or commit number this happens with?

**Comment by DavidBruchmann** [comment]
Yeah sure, but not public as it's a project-file.
Will send to the  mail mentioned on your homepage.

**Comment by DavidBruchmann** [comment]
I downloaded always the newest (master) no matter if github or composer.

**Comment by DavidBruchmann** [comment]
Probably the same like with #3 .
If you can't reproduce just close it, I can neither ;-)

**Comment by Johannestegner** [comment]
Closing due to not being able to reproduce, will try to expand the tests and see if I can get a case to fix it!
