### ISSUE TITLE
fault in Parser::next()

### ISSUE THREAD

**Issue by DavidBruchmann** [jitesoft/php-xml2array#3]
When the last element is reached, the function next() produces an error-message because `$this->values[$this->current]` is empty.
I propose just to note it like this:
```
    private function next() {
		if(isset($this->values[$this->current])){
			$out = $this->values[$this->current];
			$this->current++;
			return $out;
		}
    }
```

**Comment by DavidBruchmann** [comment]
Happens only when project is cloned instead of installed by composer.

**Comment by Johannestegner** [comment]
Which version are you using when installed by composer alt cloning the repository?

**Comment by DavidBruchmann** [comment]
With composer I used the most recent version.
But the bug appeared only when I downloaded from github (by cloning), then the autoloader is not working and I included the files as required as you can see in my other post about the example.

**Comment by Johannestegner** [comment]
I run the code with the xml file you supplied me with through email, but I can not reproduce this case.
Do you use that xml when this happens or another?

Looking at the code, the `next` method should only be called as long as the type is not equal to `self::CLOSE` (and then one last time to hit the `self::CLOSE` node).
Could it be that the xml is malformed (even though I would think that the parser should catch this before the parsing even begins).

**Comment by DavidBruchmann** [comment]
I debugged the value with `var_dump($this->current)` and it returned `NULL` before I filed the issue.  
The pity is I can't reproduce it now anymore too.  
Just close the issue and when I stumble upon it again I can reopen and provide further details.
