### ISSUE TITLE
feature: reverse function

### ISSUE THREAD

**Issue by DavidBruchmann** [jitesoft/php-xml2array#4]
Would be nice having a reverse function for producing XML out of the produced files again.
Would be a test too, if everything is the same then.

**Comment by Johannestegner** [comment]
Do I understand this feature request correct that you would like a way to convert the parsed data into a new XML file?  
As of yet, I have focused on only parse the XML into more manageable structures.  
I can not decide on if I want this package to also include to-xml also...

Question is if there should be another package for converting the array, json and/or NodeTree into a XML string (or even `simple_xml` structure) and then a package which includes both... Or if this package should also include this code.  
I will have to think about this for a bit! :)

**Comment by DavidBruchmann** [comment]
Yeah, as your code looks so easy smart and simple I think it can't be too difficult but about the xml2array problem exists so much code that shows that the problem is not so easy as it seems perhaps ;-)
I struggled too a bit and was glad having found your repository as good example but also as base for further things.

**Comment by Johannestegner** [comment]
Closing this for now, will likely create a new package to serialise the structure to xml again.

**Comment by DavidBruchmann** [comment]
hehe, I was forced to shift to something else too ;-)
