### ISSUE TITLE
Isn't "Node tree" and "Json string" the same?

### ISSUE THREAD

**Issue by DavidBruchmann** [jitesoft/php-xml2array#5]
The file comparison of the corresponding results on base of a quite huge XML-file never shows any difference. So is there any difference I don't see?

**Comment by Johannestegner** [comment]
The `NodeTree` structure is a tree structure using the `Node` class for each element. It represents the same data as the `json` or `array` output, but the `NodeTree` uses a easy-to iterate structure.  
When dumping the `Node` structure by using the `__toString` method, it will return the data as a json string for easier reading.  So it might be that you are comparing the json output with the string representation of the Node structure.

I might have misunderstood your question, please let me know if such is the case!

**Comment by DavidBruchmann** [comment]
Thank's.
So Json is only the representation of the node-structure.
Question is if there have to be two options for output available, if output is the same, it's not disturbing but only a bit confusing ;-)

**Comment by Johannestegner** [comment]
I guess you are right, I do think that the `__debugInfo` magic-method should be implemented and used to return array or string representation rather than the `__toString` method.  
I will change this for next release :)
